apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-consumer
  template:
    metadata:
      labels:
        app: producer-consumer
    spec:
      containers:
        - name: producer-consumer
          image: producer-consumer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          command: ["/root/app"]
          args:
            ["--producers=10", "--consumers=5", "--rps=500", "--duration=1"]
---
apiVersion: v1
kind: Service
metadata:
  name: producer-consumer-service
spec:
  selector:
    app: producer-consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
